// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yHI6iEH_TAQuoyF5xVCsXqF5_ecBcOo',
    appId: '1:520431149532:web:53eb4418e3943e3bdc6f19',
    messagingSenderId: '520431149532',
    projectId: 'mynotes-8e10d',
    authDomain: 'mynotes-8e10d.firebaseapp.com',
    storageBucket: 'mynotes-8e10d.appspot.com',
    measurementId: 'G-DK813RBH9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGL73zIzX-_iZKoKxRDgHmjYx36ENZQDk',
    appId: '1:520431149532:android:6db108808057e8e4dc6f19',
    messagingSenderId: '520431149532',
    projectId: 'mynotes-8e10d',
    storageBucket: 'mynotes-8e10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxJuhbxYU0DMy-i8gED95KQCojVHHaaw',
    appId: '1:520431149532:ios:8712da0885c00a96dc6f19',
    messagingSenderId: '520431149532',
    projectId: 'mynotes-8e10d',
    storageBucket: 'mynotes-8e10d.appspot.com',
    iosBundleId: 'com.devorion.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzxJuhbxYU0DMy-i8gED95KQCojVHHaaw',
    appId: '1:520431149532:ios:83afe645b64d2ee9dc6f19',
    messagingSenderId: '520431149532',
    projectId: 'mynotes-8e10d',
    storageBucket: 'mynotes-8e10d.appspot.com',
    iosBundleId: 'com.devorion.mynotes.RunnerTests',
  );
}
